# Generated by Django 5.0.2 on 2024-04-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='articles.member'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='articles.member'),
        ),
    ]
