# Generated by Django 5.0.2 on 2024-05-23 06:22

import articles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='featured_image',
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=articles.models.article_images_upload)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
