# Generated by Django 5.0.2 on 2024-05-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_featured_image_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
