# Generated by Django 5.0.2 on 2024-05-27 09:59

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_images_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=articles.models.article_images_upload),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
